### ISSUE TITLE
Update to 1.19.4 Please

### ISSUE THREAD

**Issue by sternschnaube** [spoorn/StepItUp#1] opened 2023-04-19 17:13 UTC
java.lang.IllegalAccessError: class net.minecraft.class_746 tried to access private field net.minecraft.class_1297.field_6013 (net.minecraft.class_746 and net.minecraft.class_1297 are in unnamed module of loader net.fabricmc.loader.impl.launch.knot.KnotClassLoader @4d49af10)
	at net.minecraft.class_746.handler$ibk000$stepitup$enableStepUp(class_746.java:11330)
	at net.minecraft.class_746.method_5784(class_746.java)
	at net.minecraft.class_1309.method_26318(class_1309.java:2293)
	at net.minecraft.class_1309.method_6091(class_1309.java:2212)
	at net.minecraft.class_1657.method_6091(class_1657.java:1609)
	at net.minecraft.class_1309.method_6007(class_1309.java:2698)
	at net.minecraft.class_1657.method_6007(class_1657.java:570)
	at net.minecraft.class_746.method_6007(class_746.java:844)
	at net.minecraft.class_1309.method_5773(class_1309.java:2400)
	at net.minecraft.class_1657.method_5773(class_1657.java:282)
	at net.minecraft.class_742.method_5773(class_742.java:2136)
	at net.minecraft.class_746.method_5773(class_746.java:217)
	at net.minecraft.class_638.method_18646(class_638.java:269)
	at net.minecraft.class_1937.method_18472(class_1937.java:488)
	at net.minecraft.class_638.method_32124(class_638.java:252)
	at net.minecraft.class_5574.method_31791(class_5574.java:54)
	at net.minecraft.class_638.method_18116(class_638.java:248)
	at net.minecraft.class_310.method_1574(class_310.java:1902)
	at net.minecraft.class_310.method_1523(class_310.java:1180)
	at net.minecraft.class_310.method_1514(class_310.java:801)
	at net.minecraft.client.main.Main.main(Main.java:237)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:462)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

**Comment by spoorn** [comment] 2023-07-02 22:11
Dupe of https://github.com/spoorn/StepItUp/issues/3, fixed now

**Closed by spoorn** 2023-07-02 22:11 UTC
